#!/usr/bin/env Rscript

# =============================================================================
# V62.1 matched-non-CO2-forcing Hector 3.5.0 experiment
#
# Purpose
# -------
# Run two Hector carbon-cycle/climate branches:
#
#   1. removal ON  = V62 canonical CDR trajectory
#   2. removal OFF = identical gross emissions, but zero CDR
#
# The common non-CO2 forcing target is generated by the FaIR job and supplied
# in:
#
#   fair_matched_nonco2_forcing.csv
#
# For each branch, Hector's total radiative forcing constraint is solved
# iteratively so that:
#
#   Hector RF_TOTAL(year) - Hector RF_CO2(year)
#
# equals:
#
#   FaIR matched non-CO2 forcing target(year)
#
# for every year from 2027 through 2300.
#
# IMPORTANT:
# ---------
# CO2 forcing is NOT harmonized between Hector and FaIR.
#
# Hector retains:
#   - its own carbon cycle
#   - its own atmospheric CO2 response
#   - its own historical carbon pools
#   - its own CO2 radiative-forcing formulation
#   - its own temperature response
#
# Only future non-CO2 forcing is harmonized.
#
# Solver change:
# --------------
# The previous implementation used an undamped fixed-point update:
#
#     constraint <- rfco2 + target
#
# That can oscillate because changing total forcing changes temperature,
# carbon-cycle feedbacks, atmospheric CO2, and therefore RF_CO2.
#
# This version uses an adaptive under-relaxed fixed-point solver with
# backtracking. The scientific experiment is unchanged.
#
# Acceptance tolerance remains:
#
#     1e-5 W/m2
#
# =============================================================================


suppressPackageStartupMessages(library(hector))
suppressPackageStartupMessages(library(jsonlite))


# -----------------------------------------------------------------------------
# Error handling
# -----------------------------------------------------------------------------

options(error = function() {
  cat("\n=== R TRACEBACK ===\n", file = stderr())
  traceback(30)
  quit(save = "no", status = 1, runLast = FALSE)
})


say <- function(...) {
  cat(sprintf(...), "\n")
  flush.console()
}


fail <- function(...) {
  stop(sprintf(...), call. = FALSE)
}


# -----------------------------------------------------------------------------
# Require exact Hector version
# -----------------------------------------------------------------------------

hector_version <- as.character(packageVersion("hector"))

if (hector_version != "3.5.0") {
  fail(
    "Expected Hector 3.5.0; found %s",
    hector_version
  )
}

say("Using Hector %s", hector_version)


# -----------------------------------------------------------------------------
# Input files
# -----------------------------------------------------------------------------

traj_path <- "external_validation_net_co2_trajectory.csv"
target_path <- "fair_matched_nonco2_forcing.csv"


if (!file.exists(traj_path)) {
  fail("Missing %s", traj_path)
}

if (!file.exists(target_path)) {
  fail("Missing %s", target_path)
}


# =============================================================================
# LOAD AND VALIDATE V62 CANONICAL TRAJECTORY
# =============================================================================

x <- read.csv(
  traj_path,
  check.names = FALSE,
  stringsAsFactors = FALSE
)


need <- c(
  "year",
  "gross_co2_gtco2",
  "permafrost_co2_gtco2",
  "stored_carbon_reversal_gtco2",
  "cdr_gtco2",
  "net_co2_gtco2"
)


miss <- setdiff(need, names(x))

if (length(miss)) {
  fail(
    "Trajectory missing columns: %s",
    paste(miss, collapse = ", ")
  )
}


x <- x[order(x$year), ]


if (min(x$year) != 2026 || max(x$year) != 2183) {
  fail(
    "Expected canonical trajectory covering 2026-2183; found %d-%d",
    min(x$year),
    max(x$year)
  )
}


if (anyDuplicated(x$year)) {
  fail("Duplicate trajectory years")
}


# -----------------------------------------------------------------------------
# Verify canonical trajectory mass balance
# -----------------------------------------------------------------------------

mass_check <-
  x$gross_co2_gtco2 +
  x$permafrost_co2_gtco2 +
  x$stored_carbon_reversal_gtco2 -
  x$cdr_gtco2


mass_err <- max(
  abs(mass_check - x$net_co2_gtco2)
)


if (!is.finite(mass_err)) {
  fail("Trajectory mass-balance calculation produced non-finite value")
}


if (mass_err >= 1e-9) {
  fail(
    "Mass balance failed: %.12g GtCO2",
    mass_err
  )
}


say(
  "Trajectory mass-balance maximum error: %.12g GtCO2",
  mass_err
)


# =============================================================================
# EXTEND TRAJECTORY THROUGH 2300
# =============================================================================

last <- x[nrow(x), ]


if (max(x$year) < 2300) {

  yy <- (max(x$year) + 1L):2300L

  ext <- data.frame(
    year = yy,
    gross_co2_gtco2 =
      rep(last$gross_co2_gtco2, length(yy)),
    permafrost_co2_gtco2 =
      rep(last$permafrost_co2_gtco2, length(yy)),
    stored_carbon_reversal_gtco2 =
      rep(last$stored_carbon_reversal_gtco2, length(yy)),
    cdr_gtco2 =
      rep(last$cdr_gtco2, length(yy)),
    net_co2_gtco2 =
      rep(last$net_co2_gtco2, length(yy))
  )

  x <- rbind(
    x[, names(ext)],
    ext
  )
}


yrs <- as.numeric(x$year)


if (!identical(yrs, as.numeric(2026:2300))) {
  fail(
    "Extended trajectory must contain every annual year 2026-2300"
  )
}


say(
  "Extended Hector trajectory covers %d-%d",
  min(yrs),
  max(yrs)
)


# =============================================================================
# LOAD FAIR-DERIVED COMMON NON-CO2 FORCING TARGET
# =============================================================================

ft <- read.csv(
  target_path,
  check.names = FALSE,
  stringsAsFactors = FALSE
)


required_forcing_columns <- c(
  "year",
  "matched_nonco2_forcing_wm2"
)


if (!all(required_forcing_columns %in% names(ft))) {
  fail(
    "Target forcing CSV has wrong columns; required: %s",
    paste(required_forcing_columns, collapse = ", ")
  )
}


ft <- ft[order(ft$year), ]


if (anyDuplicated(ft$year)) {
  fail("Duplicate years in common non-CO2 forcing target")
}


match_years <- 2027:2300


target <- ft$matched_nonco2_forcing_wm2[
  match(match_years, ft$year)
]


if (
  length(target) != length(match_years) ||
  any(!is.finite(target))
) {
  fail(
    "Common non-CO2 forcing target missing/non-finite over 2027-2300"
  )
}


say(
  "Loaded common non-CO2 target for %d-%d",
  min(match_years),
  max(match_years)
)


# =============================================================================
# CONVERT V62 CO2 FLOWS TO PgC
# =============================================================================

# Molecular conversion:
#
# GtCO2 * 12.011 / 44.009 = PgC

co2_to_c <- 12.011 / 44.009


gross_source_gtco2 <-
  x$gross_co2_gtco2 +
  x$permafrost_co2_gtco2 +
  x$stored_carbon_reversal_gtco2


gross_c <- gross_source_gtco2 * co2_to_c
cdr_c <- x$cdr_gtco2 * co2_to_c
zero_c <- rep(0, length(yrs))


if (
  any(!is.finite(gross_c)) ||
  any(!is.finite(cdr_c))
) {
  fail("Non-finite converted carbon trajectory")
}


# =============================================================================
# HECTOR CONFIGURATION
# =============================================================================

ini <- system.file(
  "input",
  "hector_ssp245.ini",
  package = "hector"
)


if (!nzchar(ini) || !file.exists(ini)) {
  fail("hector_ssp245.ini not found")
}


say(
  "Using Hector configuration: %s",
  ini
)


unit_ffi <- getunits(FFI_EMISSIONS())
unit_luc <- getunits(LUC_EMISSIONS())
unit_luc_uptake <- getunits(LUC_UPTAKE())
unit_daccs <- getunits(DACCS_UPTAKE())


# =============================================================================
# HECTOR HELPERS
# =============================================================================

set_checked <- function(
  core,
  dates,
  var,
  values,
  unit,
  label
) {

  if (length(dates) != length(values)) {
    fail(
      "setvar length mismatch for %s: %d dates, %d values",
      label,
      length(dates),
      length(values)
    )
  }

  if (any(!is.finite(values))) {
    fail(
      "Non-finite values supplied to setvar for %s",
      label
    )
  }

  tryCatch(
    setvar(
      core,
      dates,
      var,
      values,
      unit
    ),
    error = function(e) {
      fail(
        "setvar failed for %s: %s",
        label,
        conditionMessage(e)
      )
    }
  )
}


fetch_one <- function(df, varname) {

  z <- df[
    df$variable == varname,
    c("year", "value")
  ]

  z <- z[order(z$year), ]

  z
}


extract_matched <- function(df, years, label) {

  ans <- df$value[
    match(
      years,
      df$year
    )
  ]

  if (
    length(ans) != length(years) ||
    any(!is.finite(ans))
  ) {
    fail(
      "Missing/non-finite %s values over %d-%d",
      label,
      min(years),
      max(years)
    )
  }

  ans
}


# =============================================================================
# RUN ONE HECTOR REALIZATION
# =============================================================================

run_once <- function(
  label,
  removal_on,
  ftotal_constraint = NULL
) {

  core <- newcore(
    ini,
    suppresslogging = TRUE,
    name = label
  )


  on.exit(
    try(
      shutdown(core),
      silent = TRUE
    ),
    add = TRUE
  )


  # ---------------------------------------------------------------------------
  # First run through 2025 using Hector's standard SSP2-4.5 configuration.
  # This preserves Hector's own historical state and carbon pools.
  # ---------------------------------------------------------------------------

  invisible(
    run(
      core,
      2025
    )
  )


  # ---------------------------------------------------------------------------
  # From 2026 onward, impose the V62 carbon trajectory.
  #
  # Gross source includes:
  #   gross anthropogenic CO2
  #   + permafrost CO2
  #   + stored-carbon reversals
  #
  # Land-use emissions/uptake are zeroed here because those terms have already
  # been incorporated explicitly in the canonical external trajectory.
  # ---------------------------------------------------------------------------

  set_checked(
    core,
    yrs,
    FFI_EMISSIONS(),
    gross_c,
    unit_ffi,
    "FFI gross source"
  )


  set_checked(
    core,
    yrs,
    LUC_EMISSIONS(),
    zero_c,
    unit_luc,
    "LUC emissions=0"
  )


  set_checked(
    core,
    yrs,
    LUC_UPTAKE(),
    zero_c,
    unit_luc_uptake,
    "LUC uptake=0"
  )


  set_checked(
    core,
    yrs,
    DACCS_UPTAKE(),
    if (removal_on) cdr_c else zero_c,
    unit_daccs,
    if (removal_on) {
      "DACCS=V62 CDR"
    } else {
      "DACCS=0"
    }
  )


  # ---------------------------------------------------------------------------
  # Apply total-radiative-forcing constraint beginning in 2027.
  #
  # 2026 remains unconstrained so both ON and OFF branches share the same
  # pre-removal/common state.
  # ---------------------------------------------------------------------------

  if (!is.null(ftotal_constraint)) {

    if (
      length(ftotal_constraint) !=
      length(match_years)
    ) {
      fail(
        "Bad Ftot constraint length: expected %d, found %d",
        length(match_years),
        length(ftotal_constraint)
      )
    }


    if (any(!is.finite(ftotal_constraint))) {
      fail(
        "Non-finite Ftot constraint supplied"
      )
    }


    set_checked(
      core,
      match_years,
      FTOT_CONSTRAIN(),
      ftotal_constraint,
      "W/m2",
      "matched Ftot constraint"
    )
  }


  # ---------------------------------------------------------------------------
  # Finish Hector through 2300.
  # ---------------------------------------------------------------------------

  invisible(
    run(
      core,
      2300
    )
  )


  # ---------------------------------------------------------------------------
  # Fetch state and forcing variables.
  # ---------------------------------------------------------------------------

  out <- fetchvars(
    core,
    yrs,
    vars = c(
      CONCENTRATIONS_CO2(),
      GLOBAL_TAS(),
      RF_CO2(),
      RF_TOTAL()
    )
  )


  co2 <- fetch_one(
    out,
    CONCENTRATIONS_CO2()
  )


  tas <- fetch_one(
    out,
    GLOBAL_TAS()
  )


  rfco2 <- fetch_one(
    out,
    RF_CO2()
  )


  rftot <- fetch_one(
    out,
    RF_TOTAL()
  )


  # ---------------------------------------------------------------------------
  # Basic output validation.
  # ---------------------------------------------------------------------------

  for (
    item in list(
      CO2 = co2,
      TAS = tas,
      RF_CO2 = rfco2,
      RF_TOTAL = rftot
    )
  ) {

    if (
      nrow(item) != length(yrs) ||
      !identical(
        as.numeric(item$year),
        yrs
      ) ||
      any(!is.finite(item$value))
    ) {
      fail(
        "Malformed/non-finite Hector output in %s",
        label
      )
    }
  }


  list(
    output = out,
    co2 = co2,
    tas = tas,
    rfco2 = rfco2,
    rftot = rftot
  )
}


# =============================================================================
# EVALUATE ONE FORCING-CONSTRAINT REALIZATION
# =============================================================================

evaluate_constraint <- function(
  z,
  constraint
) {

  rfco2 <- extract_matched(
    z$rfco2,
    match_years,
    "Hector RF_CO2"
  )


  rftot <- extract_matched(
    z$rftot,
    match_years,
    "Hector RF_TOTAL"
  )


  # What Hector effectively treats as non-CO2 forcing:
  #
  # RF_TOTAL - RF_CO2

  effective_nonco2 <- rftot - rfco2


  residual <-
    effective_nonco2 -
    target


  max_res <- max(
    abs(residual)
  )


  worst_index <- which.max(
    abs(residual)
  )


  worst_year <-
    match_years[worst_index]


  worst_residual <-
    residual[worst_index]


  # Hector's documented Ftot constraint should make RF_TOTAL follow the
  # supplied constraint. Record any discrepancy as an audit quantity.

  constraint_tracking_error <- max(
    abs(
      rftot -
      constraint
    )
  )


  # Fixed-point target:
  #
  # If RF_TOTAL = constraint, the condition
  #
  #   RF_TOTAL - RF_CO2 = target
  #
  # implies
  #
  #   constraint = RF_CO2 + target

  fixed_point <-
    rfco2 +
    target


  max_fixed_point_step <- max(
    abs(
      fixed_point -
      constraint
    )
  )


  list(
    run = z,
    rfco2 = rfco2,
    rftot = rftot,
    effective_nonco2 = effective_nonco2,
    residual = residual,
    max_res = max_res,
    worst_year = worst_year,
    worst_residual = worst_residual,
    constraint_tracking_error =
      constraint_tracking_error,
    fixed_point = fixed_point,
    max_fixed_point_step =
      max_fixed_point_step
  )
}


# =============================================================================
# RECORD SOLVER ITERATION
# =============================================================================

history_record <- function(
  iteration,
  trial,
  alpha,
  accepted,
  assessment
) {

  list(
    iteration = as.integer(iteration),
    trial = as.integer(trial),
    alpha = as.numeric(alpha),
    accepted = isTRUE(accepted),

    max_abs_nonco2_error_wm2 =
      as.numeric(
        assessment$max_res
      ),

    max_constraint_update_wm2 =
      as.numeric(
        assessment$max_fixed_point_step
      ),

    worst_year =
      as.integer(
        assessment$worst_year
      ),

    worst_residual_wm2 =
      as.numeric(
        assessment$worst_residual
      ),

    constraint_tracking_error_wm2 =
      as.numeric(
        assessment$constraint_tracking_error
      )
  )
}


# =============================================================================
# ADAPTIVE MATCHED-FORCING SOLVER
# =============================================================================

fit_case <- function(
  label,
  removal_on,

  # Keep original scientific acceptance tolerance.
  tol = 1e-5,

  # Maximum accepted solver iterations.
  max_iter = 100,

  # Initial under-relaxation.
  alpha_init = 0.25,

  # Largest permitted step.
  alpha_max = 1.0,

  # Smallest backtracking step.
  alpha_min = 1 / 4096,

  # Number of backtracking attempts per iteration.
  max_backtrack = 14
) {

  say("")
  say("============================================================")
  say("Starting %s", label)
  say("============================================================")


  # ---------------------------------------------------------------------------
  # STEP 1 — Unconstrained seed
  # ---------------------------------------------------------------------------

  say(
    "%s: running unconstrained seed",
    label
  )


  seed <- run_once(
    paste0(
      label,
      " seed"
    ),
    removal_on,
    NULL
  )


  rf_seed <- extract_matched(
    seed$rfco2,
    match_years,
    "seed CO2 forcing"
  )


  # Initial total-forcing guess:
  #
  # Hector seed CO2 forcing + common FaIR non-CO2 forcing.

  constraint <-
    rf_seed +
    target


  if (any(!is.finite(constraint))) {
    fail(
      "Non-finite initial forcing constraint for %s",
      label
    )
  }


  # ---------------------------------------------------------------------------
  # STEP 2 — Evaluate initial constrained realization
  # ---------------------------------------------------------------------------

  say(
    "%s: evaluating initial matched-forcing constraint",
    label
  )


  current_run <- run_once(
    sprintf(
      "%s initial",
      label
    ),
    removal_on,
    constraint
  )


  current <- evaluate_constraint(
    current_run,
    constraint
  )


  history <- list()


  history[[length(history) + 1L]] <-
    history_record(
      iteration = 0,
      trial = 0,
      alpha = 0,
      accepted = TRUE,
      assessment = current
    )


  say(
    "%s initial max |effective non-CO2 - target| = %.9g W/m2 at year %d",
    label,
    current$max_res,
    current$worst_year
  )


  say(
    "%s initial Ftot constraint tracking error = %.9g W/m2",
    label,
    current$constraint_tracking_error
  )


  # ---------------------------------------------------------------------------
  # If the first constrained realization already matches, we are finished.
  # ---------------------------------------------------------------------------

  if (current$max_res <= tol) {

    say(
      "%s converged immediately: %.9g <= %.9g W/m2",
      label,
      current$max_res,
      tol
    )


    return(
      list(
        run = current$run,
        history = history,
        forcing_error = current$max_res,
        final_constraint = constraint,
        solver = "adaptive-under-relaxed-fixed-point-with-backtracking"
      )
    )
  }


  # ---------------------------------------------------------------------------
  # Adaptive relaxation state
  # ---------------------------------------------------------------------------

  alpha <- alpha_init


  # ---------------------------------------------------------------------------
  # Main solver
  # ---------------------------------------------------------------------------

  for (it in seq_len(max_iter)) {

    say("")
    say(
      "%s solver iteration %d",
      label,
      it
    )


    say(
      "  current maximum residual = %.9g W/m2 at year %d",
      current$max_res,
      current$worst_year
    )


    # -------------------------------------------------------------------------
    # Fixed-point correction.
    #
    # Existing code effectively did:
    #
    #   constraint <- current$fixed_point
    #
    # which is equivalent to alpha = 1.
    #
    # Instead:
    #
    #   candidate =
    #       constraint +
    #       alpha * (fixed_point - constraint)
    #
    # -------------------------------------------------------------------------

    direction <-
      current$fixed_point -
      constraint


    direction_norm <- max(
      abs(direction)
    )


    if (!is.finite(direction_norm)) {
      fail(
        "%s produced non-finite solver direction",
        label
      )
    }


    if (direction_norm == 0) {
      fail(
        paste0(
          "%s solver stalled with zero constraint correction, ",
          "but residual remains %.9g W/m2"
        ),
        label,
        current$max_res
      )
    }


    # Start conservatively but allow step size to grow after successful
    # iterations.

    trial_alpha <- min(
      alpha_max,
      alpha * 1.35
    )


    accepted <- FALSE

    best_assessment <- NULL
    best_constraint <- NULL
    best_alpha <- NA_real_
    best_trial <- NA_integer_


    # -------------------------------------------------------------------------
    # Backtracking line search
    # -------------------------------------------------------------------------

    for (bt in 0:max_backtrack) {

      if (trial_alpha < alpha_min) {
        break
      }


      candidate_constraint <-
        constraint +
        trial_alpha *
        direction


      if (
        any(
          !is.finite(
            candidate_constraint
          )
        )
      ) {
        fail(
          "%s generated non-finite candidate forcing constraint",
          label
        )
      }


      say(
        "  trial %d: alpha = %.9g",
        bt + 1L,
        trial_alpha
      )


      trial_run <- run_once(
        sprintf(
          "%s iter%d trial%d",
          label,
          it,
          bt + 1L
        ),
        removal_on,
        candidate_constraint
      )


      trial_assessment <-
        evaluate_constraint(
          trial_run,
          candidate_constraint
        )


      say(
        paste0(
          "    max residual = %.9g W/m2 ",
          "(year %d; signed residual %.9g)"
        ),
        trial_assessment$max_res,
        trial_assessment$worst_year,
        trial_assessment$worst_residual
      )


      # Keep track of best attempted point even if we backtrack further.

      if (
        is.null(best_assessment) ||
        trial_assessment$max_res <
        best_assessment$max_res
      ) {

        best_assessment <-
          trial_assessment

        best_constraint <-
          candidate_constraint

        best_alpha <-
          trial_alpha

        best_trial <-
          bt + 1L
      }


      # -----------------------------------------------------------------------
      # Accept immediately if tolerance is achieved.
      # -----------------------------------------------------------------------

      if (
        trial_assessment$max_res <= tol
      ) {

        history[
          [length(history) + 1L]
        ] <-
          history_record(
            iteration = it,
            trial = bt + 1L,
            alpha = trial_alpha,
            accepted = TRUE,
            assessment =
              trial_assessment
          )


        constraint <-
          candidate_constraint

        current <-
          trial_assessment

        alpha <-
          trial_alpha

        accepted <- TRUE

        say(
          "    ACCEPTED: tolerance reached"
        )

        break
      }


      # -----------------------------------------------------------------------
      # Normal acceptance rule:
      #
      # Require a genuine decrease in maximum absolute forcing mismatch.
      #
      # A tiny numerical allowance prevents floating-point noise from
      # incorrectly rejecting an otherwise equal/improved state.
      # -----------------------------------------------------------------------

      improvement_threshold <-
        max(
          1e-12,
          current$max_res * 1e-8
        )


      improved <-
        trial_assessment$max_res <
        (
          current$max_res -
          improvement_threshold
        )


      history[
        [length(history) + 1L]
      ] <-
        history_record(
          iteration = it,
          trial = bt + 1L,
          alpha = trial_alpha,
          accepted = improved,
          assessment =
            trial_assessment
        )


      if (improved) {

        constraint <-
          candidate_constraint

        current <-
          trial_assessment

        alpha <-
          trial_alpha

        accepted <- TRUE

        say(
          "    ACCEPTED: residual decreased"
        )

        break
      }


      # -----------------------------------------------------------------------
      # Residual did not decrease. Reduce the step and retry from the same
      # accepted starting point.
      # -----------------------------------------------------------------------

      say(
        "    rejected; backtracking"
      )


      trial_alpha <-
        trial_alpha / 2
    }


    # -------------------------------------------------------------------------
    # If none of the normal trial steps was accepted, inspect the best one.
    # -------------------------------------------------------------------------

    if (!accepted) {

      if (
        !is.null(best_assessment) &&
        best_assessment$max_res <
        current$max_res
      ) {

        say(
          paste0(
            "  accepting best backtracking trial ",
            "alpha=%.9g, residual=%.9g W/m2"
          ),
          best_alpha,
          best_assessment$max_res
        )


        constraint <-
          best_constraint

        current <-
          best_assessment

        alpha <-
          best_alpha

        accepted <- TRUE


        history[
          [length(history) + 1L]
        ] <-
          history_record(
            iteration = it,
            trial = best_trial,
            alpha = best_alpha,
            accepted = TRUE,
            assessment =
              best_assessment
          )
      }
    }


    # -------------------------------------------------------------------------
    # If no step decreases the residual even after aggressive damping, do not
    # silently continue. Produce a specific numerical failure.
    # -------------------------------------------------------------------------

    if (!accepted) {

      fail(
        paste0(
          "%s matched-forcing solver stalled at iteration %d. ",
          "Current residual %.9g W/m2 at year %d. ",
          "No backtracking step down to alpha %.9g improved the solution."
        ),
        label,
        it,
        current$max_res,
        current$worst_year,
        alpha_min
      )
    }


    say(
      "%s accepted iteration %d: max residual %.9g W/m2",
      label,
      it,
      current$max_res
    )


    # -------------------------------------------------------------------------
    # Convergence test
    # -------------------------------------------------------------------------

    if (
      current$max_res <= tol
    ) {

      say(
        "%s CONVERGED after %d solver iterations: %.9g <= %.9g W/m2",
        label,
        it,
        current$max_res,
       
