#!/usr/bin/env Rscript

# =============================================================================
# V62.1 matched-non-CO2-forcing Hector 3.5.0 experiment
#
# Runs two Hector carbon-cycle/climate branches:
#
#   1. removal ON  = V62 canonical CDR trajectory
#   2. removal OFF = identical gross emissions, but zero CDR
#
# The common non-CO2 forcing target is generated by the FaIR job and supplied
# in fair_matched_nonco2_forcing.csv.
#
# Hector's total-radiative-forcing constraint is iterated to self-consistency
# so that, for each carbon branch:
#
#   Hector RF_TOTAL(year) - Hector RF_CO2(year)
#
# equals:
#
#   common FaIR-derived non-CO2 forcing target(year)
#
# from 2027 through 2300.
#
# IMPORTANT:
#
# CO2 forcing is NOT harmonized between Hector and FaIR.
#
# Hector retains:
#   - its own carbon cycle
#   - its own atmospheric CO2 response
#   - its own historical carbon pools
#   - its own CO2 radiative-forcing formulation
#   - its own temperature response
#
# Only future non-CO2 forcing is harmonized.
#
# NUMERICAL SOLVER:
#
# The former solver applied the full fixed-point correction:
#
#   constraint <- next_constraint
#
# That can oscillate because changing total forcing can alter temperature,
# carbon-cycle feedbacks, atmospheric CO2, and therefore RF_CO2.
#
# This version uses under-relaxation:
#
#   constraint <- constraint +
#                 relax * (next_constraint - constraint)
#
# with relax = 0.25.
#
# This changes only numerical convergence. It does NOT alter the V62
# emissions/removal trajectory, Hector physics, the common forcing target,
# or the scientific acceptance threshold.
#
# Scientific forcing-match acceptance tolerance remains:
#
#   1e-5 W/m2
#
# =============================================================================


suppressPackageStartupMessages(library(hector))
suppressPackageStartupMessages(library(jsonlite))


# =============================================================================
# ERROR HANDLING
# =============================================================================

options(error = function() {
  cat("\n=== R TRACEBACK ===\n", file = stderr())
  traceback(30)
  quit(save = "no", status = 1, runLast = FALSE)
})


say <- function(...) {
  cat(sprintf(...), "\n")
  flush.console()
}


fail <- function(...) {
  stop(sprintf(...), call. = FALSE)
}


# =============================================================================
# REQUIRE EXACT HECTOR VERSION
# =============================================================================

hector_version <- as.character(packageVersion("hector"))

if (hector_version != "3.5.0") {
  fail(
    "Expected Hector 3.5.0; found %s",
    hector_version
  )
}

say("Using Hector %s", hector_version)


# =============================================================================
# INPUT FILES
# =============================================================================

traj_path <- "external_validation_net_co2_trajectory.csv"
target_path <- "fair_matched_nonco2_forcing.csv"


if (!file.exists(traj_path)) {
  fail("Missing %s", traj_path)
}

if (!file.exists(target_path)) {
  fail("Missing %s", target_path)
}


# =============================================================================
# LOAD AND VALIDATE V62 CANONICAL TRAJECTORY
# =============================================================================

x <- read.csv(
  traj_path,
  check.names = FALSE,
  stringsAsFactors = FALSE
)


need <- c(
  "year",
  "gross_co2_gtco2",
  "permafrost_co2_gtco2",
  "stored_carbon_reversal_gtco2",
  "cdr_gtco2",
  "net_co2_gtco2"
)


miss <- setdiff(
  need,
  names(x)
)


if (length(miss)) {
  fail(
    "Trajectory missing columns: %s",
    paste(miss, collapse = ", ")
  )
}


x <- x[
  order(x$year),
]


if (
  min(x$year) != 2026 ||
  max(x$year) != 2183
) {
  fail(
    "Expected canonical trajectory covering 2026-2183; found %d-%d",
    min(x$year),
    max(x$year)
  )
}


if (anyDuplicated(x$year)) {
  fail("Duplicate trajectory years")
}


# -----------------------------------------------------------------------------
# Verify canonical trajectory mass balance
# -----------------------------------------------------------------------------

mass_check <-
  x$gross_co2_gtco2 +
  x$permafrost_co2_gtco2 +
  x$stored_carbon_reversal_gtco2 -
  x$cdr_gtco2


mass_err <- max(
  abs(
    mass_check -
    x$net_co2_gtco2
  )
)


if (!is.finite(mass_err)) {
  fail(
    "Trajectory mass-balance calculation produced non-finite value"
  )
}


if (mass_err >= 1e-9) {
  fail(
    "Mass balance failed: %.12g GtCO2",
    mass_err
  )
}


say(
  "Trajectory mass-balance maximum error: %.12g GtCO2",
  mass_err
)


# =============================================================================
# EXTEND TRAJECTORY THROUGH 2300
# =============================================================================

last <- x[
  nrow(x),
]


if (max(x$year) < 2300) {

  yy <- (max(x$year) + 1L):2300L

  ext <- data.frame(
    year = yy,

    gross_co2_gtco2 =
      rep(
        last$gross_co2_gtco2,
        length(yy)
      ),

    permafrost_co2_gtco2 =
      rep(
        last$permafrost_co2_gtco2,
        length(yy)
      ),

    stored_carbon_reversal_gtco2 =
      rep(
        last$stored_carbon_reversal_gtco2,
        length(yy)
      ),

    cdr_gtco2 =
      rep(
        last$cdr_gtco2,
        length(yy)
      ),

    net_co2_gtco2 =
      rep(
        last$net_co2_gtco2,
        length(yy)
      )
  )

  x <- rbind(
    x[, names(ext)],
    ext
  )
}


yrs <- as.numeric(
  x$year
)


if (
  !identical(
    yrs,
    as.numeric(2026:2300)
  )
) {
  fail(
    "Extended trajectory must contain every annual year 2026-2300"
  )
}


say(
  "Extended Hector trajectory covers %d-%d",
  min(yrs),
  max(yrs)
)


# =============================================================================
# LOAD FAIR-DERIVED COMMON NON-CO2 FORCING TARGET
# =============================================================================

ft <- read.csv(
  target_path,
  check.names = FALSE,
  stringsAsFactors = FALSE
)


required_forcing_columns <- c(
  "year",
  "matched_nonco2_forcing_wm2"
)


if (
  !all(
    required_forcing_columns %in%
    names(ft)
  )
) {
  fail(
    "Target forcing CSV has wrong columns; required: %s",
    paste(
      required_forcing_columns,
      collapse = ", "
    )
  )
}


ft <- ft[
  order(ft$year),
]


if (anyDuplicated(ft$year)) {
  fail(
    "Duplicate years in common non-CO2 forcing target"
  )
}


match_years <- 2027:2300


target <-
  ft$matched_nonco2_forcing_wm2[
    match(
      match_years,
      ft$year
    )
  ]


if (
  length(target) != length(match_years) ||
  any(!is.finite(target))
) {
  fail(
    "Common non-CO2 forcing target missing/non-finite over 2027-2300"
  )
}


say(
  "Loaded common non-CO2 forcing target for %d-%d",
  min(match_years),
  max(match_years)
)


# =============================================================================
# CONVERT V62 CO2 FLOWS TO PgC
# =============================================================================

# Molecular conversion:
#
# GtCO2 * 12.011 / 44.009 = PgC

co2_to_c <- 12.011 / 44.009


gross_source_gtco2 <-
  x$gross_co2_gtco2 +
  x$permafrost_co2_gtco2 +
  x$stored_carbon_reversal_gtco2


gross_c <-
  gross_source_gtco2 *
  co2_to_c


cdr_c <-
  x$cdr_gtco2 *
  co2_to_c


zero_c <- rep(
  0,
  length(yrs)
)


if (
  any(!is.finite(gross_c)) ||
  any(!is.finite(cdr_c))
) {
  fail(
    "Non-finite converted carbon trajectory"
  )
}


# =============================================================================
# HECTOR CONFIGURATION
# =============================================================================

ini <- system.file(
  "input",
  "hector_ssp245.ini",
  package = "hector"
)


if (
  !nzchar(ini) ||
  !file.exists(ini)
) {
  fail(
    "hector_ssp245.ini not found"
  )
}


say(
  "Using Hector configuration: %s",
  ini
)


unit_ffi <-
  getunits(
    FFI_EMISSIONS()
  )

unit_luc <-
  getunits(
    LUC_EMISSIONS()
  )

unit_luc_uptake <-
  getunits(
    LUC_UPTAKE()
  )

unit_daccs <-
  getunits(
    DACCS_UPTAKE()
  )


# =============================================================================
# HECTOR HELPERS
# =============================================================================

set_checked <- function(
  core,
  dates,
  var,
  values,
  unit,
  label
) {

  if (
    length(dates) !=
    length(values)
  ) {
    fail(
      "setvar length mismatch for %s: %d dates, %d values",
      label,
      length(dates),
      length(values)
    )
  }


  if (
    any(!is.finite(values))
  ) {
    fail(
      "Non-finite values supplied to setvar for %s",
      label
    )
  }


  tryCatch(
    setvar(
      core,
      dates,
      var,
      values,
      unit
    ),

    error = function(e) {
      fail(
        "setvar failed for %s: %s",
        label,
        conditionMessage(e)
      )
    }
  )
}


fetch_one <- function(
  df,
  varname
) {

  z <- df[
    df$variable == varname,
    c(
      "year",
      "value"
    )
  ]

  z <- z[
    order(z$year),
  ]

  z
}


extract_matched <- function(
  df,
  years,
  label
) {

  ans <- df$value[
    match(
      years,
      df$year
    )
  ]


  if (
    length(ans) != length(years) ||
    any(!is.finite(ans))
  ) {
    fail(
      "Missing/non-finite %s values over %d-%d",
      label,
      min(years),
      max(years)
    )
  }


  ans
}


# =============================================================================
# RUN ONE HECTOR REALIZATION
# =============================================================================

run_once <- function(
  label,
  removal_on,
  ftotal_constraint = NULL
) {

  core <- newcore(
    ini,
    suppresslogging = TRUE,
    name = label
  )


  on.exit(
    try(
      shutdown(core),
      silent = TRUE
    ),
    add = TRUE
  )


  # ---------------------------------------------------------------------------
  # First run through 2025 using Hector's standard SSP2-4.5 configuration.
  # This preserves Hector's own historical state and carbon pools.
  # ---------------------------------------------------------------------------

  invisible(
    run(
      core,
      2025
    )
  )


  # ---------------------------------------------------------------------------
  # From 2026 onward, impose the V62 carbon trajectory.
  #
  # Gross source includes:
  #   gross anthropogenic CO2
  #   + permafrost CO2
  #   + stored-carbon reversals
  #
  # Land-use emissions/uptake are zeroed because those terms have already been
  # incorporated explicitly in the canonical external trajectory.
  # ---------------------------------------------------------------------------

  set_checked(
    core,
    yrs,
    FFI_EMISSIONS(),
    gross_c,
    unit_ffi,
    "FFI gross source"
  )


  set_checked(
    core,
    yrs,
    LUC_EMISSIONS(),
    zero_c,
    unit_luc,
    "LUC emissions=0"
  )


  set_checked(
    core,
    yrs,
    LUC_UPTAKE(),
    zero_c,
    unit_luc_uptake,
    "LUC uptake=0"
  )


  set_checked(
    core,
    yrs,
    DACCS_UPTAKE(),
    if (removal_on) {
      cdr_c
    } else {
      zero_c
    },
    unit_daccs,
    if (removal_on) {
      "DACCS=V62 CDR"
    } else {
      "DACCS=0"
    }
  )


  # ---------------------------------------------------------------------------
  # Apply total-radiative-forcing constraint beginning in 2027.
  #
  # 2026 remains unconstrained so both ON/OFF branches retain the common
  # pre-removal state.
  # ---------------------------------------------------------------------------

  if (!is.null(ftotal_constraint)) {

    if (
      length(ftotal_constraint) !=
      length(match_years)
    ) {
      fail(
        "Bad Ftot constraint length: expected %d, found %d",
        length(match_years),
        length(ftotal_constraint)
      )
    }


    if (
      any(
        !is.finite(
          ftotal_constraint
        )
      )
    ) {
      fail(
        "Non-finite Ftot constraint supplied"
      )
    }


    set_checked(
      core,
      match_years,
      FTOT_CONSTRAIN(),
      ftotal_constraint,
      "W/m2",
      "matched Ftot constraint"
    )
  }


  # ---------------------------------------------------------------------------
  # Finish Hector through 2300.
  # ---------------------------------------------------------------------------

  invisible(
    run(
      core,
      2300
    )
  )


  # ---------------------------------------------------------------------------
  # Fetch state and forcing variables.
  # ---------------------------------------------------------------------------

  out <- fetchvars(
    core,
    yrs,
    vars = c(
      CONCENTRATIONS_CO2(),
      GLOBAL_TAS(),
      RF_CO2(),
      RF_TOTAL()
    )
  )


  co2 <- fetch_one(
    out,
    CONCENTRATIONS_CO2()
  )


  tas <- fetch_one(
    out,
    GLOBAL_TAS()
  )


  rfco2 <- fetch_one(
    out,
    RF_CO2()
  )


  rftot <- fetch_one(
    out,
    RF_TOTAL()
  )


  # ---------------------------------------------------------------------------
  # Validate returned output.
  # ---------------------------------------------------------------------------

  outputs <- list(
    CO2 = co2,
    TAS = tas,
    RF_CO2 = rfco2,
    RF_TOTAL = rftot
  )


  for (
    output_name in names(outputs)
  ) {

    item <- outputs[
      [output_name]
    ]


    if (
      nrow(item) !=
      length(yrs)
    ) {
      fail(
        "Malformed Hector %s output in %s: expected %d rows, found %d",
        output_name,
        label,
        length(yrs),
        nrow(item)
      )
    }


    if (
      !identical(
        as.numeric(item$year),
        yrs
      )
    ) {
      fail(
        "Malformed Hector %s year sequence in %s",
        output_name,
        label
      )
    }


    if (
      any(
        !is.finite(
          item$value
        )
      )
    ) {
      fail(
        "Non-finite Hector %s output in %s",
        output_name,
        label
      )
    }
  }


  list(
    output = out,
    co2 = co2,
    tas = tas,
    rfco2 = rfco2,
    rftot = rftot
  )
}


# =============================================================================
# MATCH COMMON NON-CO2 FORCING
# =============================================================================

fit_case <- function(
  label,
  removal_on,
  tol = 1e-5,
  max_iter = 100,
  relax = 0.25
) {

  say("")
  say(
    "============================================================"
  )
  say(
    "Starting %s",
    label
  )
  say(
    "============================================================"
  )


  if (
    !is.finite(relax) ||
    relax <= 0 ||
    relax > 1
  ) {
    fail(
      "Invalid relaxation factor %.9g for %s",
      relax,
      label
    )
  }


  # ---------------------------------------------------------------------------
  # Unconstrained seed.
  # ---------------------------------------------------------------------------

  say(
    "%s: running unconstrained seed",
    label
  )


  seed <- run_once(
    paste0(
      label,
      " seed"
    ),
    removal_on,
    NULL
  )


  rf_seed <- extract_matched(
    seed$rfco2,
    match_years,
    "seed CO2 forcing"
  )


  # Initial total-forcing constraint:
  #
  #   Hector CO2 forcing + common FaIR-derived non-CO2 forcing target

  constraint <-
    rf_seed +
    target


  if (
    any(
      !is.finite(
        constraint
      )
    )
  ) {
    fail(
      "Non-finite initial forcing constraint for %s",
      label
    )
  }


  history <- list()
  final <- NULL


  # ---------------------------------------------------------------------------
  # Damped fixed-point iteration.
  # ---------------------------------------------------------------------------

  for (
    it in seq_len(max_iter)
  ) {

    say(
      "%s forcing iteration %d",
      label,
      it
    )


    z <- run_once(
      sprintf(
        "%s iter%d",
        label,
        it
      ),
      removal_on,
      constraint
    )


    rfco2 <- extract_matched(
      z$rfco2,
      match_years,
      sprintf(
        "%s RF_CO2",
        label
      )
    )


    rftot <- extract_matched(
      z$rftot,
      match_years,
      sprintf(
        "%s RF_TOTAL",
        label
      )
    )


    # Hector's effective non-CO2 forcing.

    effective_nonco2 <-
      rftot -
      rfco2


    residual <-
      effective_nonco2 -
      target


    max_res <- max(
      abs(
        residual
      )
    )


    if (
      !is.finite(
        max_res
      )
    ) {
      fail(
        "Non-finite forcing residual in %s",
        label
      )
    }


    worst_index <- which.max(
      abs(
        residual
      )
    )


    worst_year <-
      match_years[
        worst_index
      ]


    worst_residual <-
      residual[
        worst_index
      ]


    # Exact fixed-point target would be:
    #
    #   RF_CO2 + common non-CO2 target
    #
    # but applying the full correction can oscillate.

    next_constraint <-
      rfco2 +
      target


    raw_update <-
      next_constraint -
      constraint


    max_raw_update <- max(
      abs(
        raw_update
      )
    )


    if (
      !is.finite(
        max_raw_update
      )
    ) {
      fail(
        "Non-finite forcing-constraint update in %s",
        label
      )
    }


    say(
      "%s matched-forcing iteration %d: max |residual| = %.9g W/m2 at year %d",
      label,
      it,
      max_res,
      worst_year
    )


    say(
      "  signed residual at worst year = %.9g W/m2",
      worst_residual
    )


    say(
      "  maximum raw fixed-point correction = %.9g W/m2",
      max_raw_update
    )


    say(
      "  relaxation factor = %.9g",
      relax
    )


    # Record iteration before convergence/update.

    history[
      [length(history) + 1L]
    ] <- list(
      iteration =
        as.integer(it),

      relaxation_factor =
        as.numeric(relax),

      max_abs_nonco2_error_wm2 =
        as.numeric(max_res),

      max_constraint_update_wm2 =
        as.numeric(max_raw_update),

      worst_year =
        as.integer(worst_year),

      worst_residual_wm2 =
        as.numeric(worst_residual)
    )


    final <- z


    # -------------------------------------------------------------------------
    # Scientific convergence test.
    #
    # DO NOT loosen this tolerance merely to obtain a green run.
    # -------------------------------------------------------------------------

    if (
      max_res <= tol
    ) {

      say(
        "%s CONVERGED after %d iterations: %.9g <= %.9g W/m2",
        label,
        it,
        max_res,
        tol
      )

      break
    }


    # -------------------------------------------------------------------------
    # UNDER-RELAXED UPDATE
    #
    # Previous unstable implementation:
    #
    #   constraint <- next_constraint
    #
    # New numerically stabilized implementation:
    #
    #   constraint <- constraint +
    #                 relax * (next_constraint - constraint)
    #
    # This affects solver convergence only.
    # -------------------------------------------------------------------------

    constraint <-
      constraint +
      relax *
      raw_update


    if (
      any(
        !is.finite(
          constraint
        )
      )
    ) {
      fail(
        "Non-finite damped forcing constraint in %s at iteration %d",
        label,
        it
      )
    }
  }


  # ---------------------------------------------------------------------------
  # Final convergence check.
  # ---------------------------------------------------------------------------

  if (
    is.null(final)
  ) {
    fail(
      "No Hector run produced for %s",
      label
    )
  }


  if (
    length(history) == 0
  ) {
    fail(
      "No Hector forcing iterations recorded for %s",
      label
    )
  }


  hlast <-
    history[
      [length(history)]
    ]


  if (
    hlast$max_abs_nonco2_error_wm2 >
    tol
  ) {
    fail(
      paste0(
        "%s matched forcing iteration did not converge after %d iterations: ",
        "%.9g > %.9g W/m2"
      ),
      label,
      max_iter,
      hlast$max_abs_nonco2_error_wm2,
      tol
    )
  }


  list(
    run = final,
    history = history,
    forcing_error =
      hlast$max_abs_nonco2_error_wm2,

    final_constraint =
      constraint,

    relaxation_factor =
      relax,

    solver =
      "under-relaxed-fixed-point"
  )
}


# =============================================================================
# RUN REMOVAL-ON AND REMOVAL-OFF HECTOR CASES
# =============================================================================

on_case <- fit_case(
  "removal-ON matched",
  TRUE
)


off_case <- fit_case(
  "removal-OFF matched",
  FALSE
)


# =============================================================================
# EXTRACT FINAL HECTOR RESULTS
# =============================================================================

co_on <-
  on_case$run$co2

co_off <-
  off_case$run$co2

tas_on <-
  on_case$run$tas

tas_off <-
  off_case$run$tas

rfco2_on <-
  on_case$run$rfco2

rfco2_off <-
  off_case$run$rfco2

rftot_on <-
  on_case$run$rftot

rftot_off <-
  off_case$run$rftot


# =============================================================================
# BUILD CO2 ATTRIBUTION TABLE
# =============================================================================

pair <- merge(
  co_on,
  co_off,
  by = "year",
  suffixes = c(
    "_on",
    "_off"
  )
)


names(pair)[
  names(pair) == "value_on"
] <- "co2_on_ppm"


names(pair)[
  names(pair) == "value_off"
] <- "co2_off_ppm"


pair <- pair[
  order(pair$year),
]


if (
  !identical(
    as.numeric(pair$year),
    yrs
  )
) {
  fail(
    "Hector paired years mismatch"
  )
}


pair$delta_co2_ppm <-
  pair$co2_off_ppm -
  pair$co2_on_ppm


cum_cdr <- cumsum(
  x$cdr_gtco2
)


pair$cumulative_cdr_gtco2 <-
  cum_cdr[
    match(
      pair$year,
      x$year
    )
  ]


# Atmospheric carbon conversion:
#
# 1 ppm CO2 = 2.124 PgC
#
# Convert PgC to GtCO2.

gtco2_per_ppm <-
  2.124 *
  (
    44.009 /
    12.011
  )


pair$apparent_response_fraction <-
  ifelse(
    pair$cumulative_cdr_gtco2 > 0,

    pair$delta_co2_ppm *
      gtco2_per_ppm /
      pair$cumulative_cdr_gtco2,

    NA_real_
  )


if (
  any(
    !is.finite(
      pair$co2_on_ppm
    )
  ) ||
  any(
    !is.finite(
      pair$co2_off_ppm
    )
  )
) {
  fail(
    "Non-finite Hector CO2"
  )
}


if (
  any(
    pair$delta_co2_ppm <
    -1e-8
  )
) {
  fail(
    "Removal ON raises CO2 above OFF beyond tolerance"
  )
}


# =============================================================================
# COMMON-STATE CHECK AT 2026
# =============================================================================

# CDR is zero in 2026, so removal ON/OFF must share the same state.

common_2026_co2 <- abs(
  pair$co2_on_ppm[
    pair$year == 2026
  ] -
  pair$co2_off_ppm[
    pair$year == 2026
  ]
)


if (
  length(common_2026_co2) != 1 ||
  common_2026_co2 > 1e-8
) {
  fail(
    "Hector 2026 common-state CO2 check failed"
  )
}


common_2026_tas <- abs(
  tas_on$value[
    tas_on$year == 2026
  ] -
  tas_off$value[
    tas_off$year == 2026
  ]
)


if (
  length(common_2026_tas) != 1 ||
  common_2026_tas > 1e-8
) {
  fail(
    "Hector 2026 common-state TAS check failed"
  )
}


# =============================================================================
# WRITE ATTRIBUTION OUTPUT
# =============================================================================

write.csv(
  pair,
  "hector_matched_attribution.csv",
  row.names = FALSE
)


# =============================================================================
# WRITE WIDE STATE/FORCING AUDIT
# =============================================================================

audit <- data.frame(
  year = yrs,

  co2_on_ppm =
    co_on$value,

  co2_off_ppm =
    co_off$value,

  tas_on_c =
    tas_on$value,

  tas_off_c =
    tas_off$value,

  rfco2_on_wm2 =
    rfco2_on$value,

  rfco2_off_wm2 =
    rfco2_off$value,

  rftot_on_wm2 =
    rftot_on$value,

  rftot_off_wm2 =
    rftot_off$value
)


target_full <-
  ft$matched_nonco2_forcing_wm2[
    match(
      yrs,
      ft$year
    )
  ]


audit$target_nonco2_wm2 <-
  target_full


audit$effective_nonco2_on_wm2 <-
  audit$rftot_on_wm2 -
  audit$rfco2_on_wm2


audit$effective_nonco2_off_wm2 <-
  audit$rftot_off_wm2 -
  audit$rfco2_off_wm2


audit$nonco2_error_on_wm2 <-
  audit$effective_nonco2_on_wm2 -
  audit$target_nonco2_wm2


audit$nonco2_error_off_wm2 <-
  audit$effective_nonco2_off_wm2 -
  audit$target_nonco2_wm2


write.csv(
  audit,
  "hector_matched_timeseries.csv",
  row.names = FALSE
)


# =============================================================================
# MILESTONE HELPER
# =============================================================================

getv <- function(
  col,
  y
) {

  z <- pair[
    pair$year == y,
    col
  ]


  if (
    length(z) != 1
  ) {
    return(
      NA_real_
    )
  }


  as.numeric(z)
}


# =============================================================================
# BUILD MILESTONE OUTPUT
# =============================================================================

milestones <- list()


for (
  yy in c(
    2040,
    2100,
    2156,
    2184,
    2200,
    2300
  )
) {

  milestones[
    [as.character(yy)]
  ] <- list(

    delta_co2_ppm =
      getv(
        "delta_co2_ppm",
        yy
      ),

    response_fraction =
      getv(
        "apparent_response_fraction",
        yy
      )
  )
}


# =============================================================================
# SUMMARY
# =============================================================================

summary <- list(

  model =
    "Hector",

  version =
    "3.5.0",

  experiment =
    paste0(
      "V62 removal-ON/OFF with FaIR-derived harmonized ",
      "non-CO2 ERF after 2026"
    ),

  common_nonco2_target =
    paste0(
      "fair_matched_nonco2_forcing.csv generated by ",
      "the FaIR matched-forcing job"
    ),

  implementation =
    paste0(
      "For each carbon branch, Hector Ftot_constrain is iterated ",
      "until RF_TOTAL - RF_CO2 equals the common target for ",
      "2027-2300. CO2 forcing remains branch-specific. ",
      "A fixed under-relaxation factor of 0.25 is used to stabilize ",
      "the numerical fixed-point iteration without changing the ",
      "scientific forcing-match tolerance."
    ),

  solver =
    "under-relaxed-fixed-point",

  solver_relaxation_factor =
    0.25,

  solver_max_iterations =
    100,

  match_starts =
    2027,

  common_state_2026_co2_abs_error_ppm =
    common_2026_co2,

  common_state_2026_tas_abs_error_c =
    common_2026_tas,

  forcing_match_tolerance_wm2 =
    1e-5,

  forcing_match_max_abs_on_wm2 =
    on_case$forcing_error,

  forcing_match_max_abs_off_wm2 =
    off_case$forcing_error,

  fit_iterations_on =
    on_case$history,

  fit_iterations_off =
    off_case$history,

  trajectory_mass_balance_max_abs_gtco2 =
    mass_err,

  canonical_cdr_2026_2183_gtco2 =
    sum(
      x$cdr_gtco2[
        x$year <= 2183
      ]
    ),

  peak_cdr_2026_2183_gtco2_per_year =
    max(
      x$cdr_gtco2[
        x$year <= 2183
      ]
    ),

  milestones =
    milestones,

  interpretation_boundary =
    paste0(
      "The future non-CO2 forcing contribution is harmonized to FaIR. ",
      "Hector retains its own carbon-cycle parameters, historical ",
      "carbon pools, atmospheric CO2 response, CO2 forcing formulation, ",
      "and temperature response. Cross-model disagreement is a result, ",
      "not an automatic failure gate."
    )
)


# =============================================================================
# WRITE JSON SUMMARY
# =============================================================================

write_json(
  summary,
  "hector_matched_summary.json",
  pretty = TRUE,
  auto_unbox = TRUE,
  digits = NA
)


cat(
  toJSON(
    summary,
    pretty = TRUE,
    auto_unbox = TRUE,
    digits = NA
  ),
  "\n"
)


say("")
say(
  "Hector matched-forcing experiment completed successfully."
)
say(
  "Removal-ON final maximum forcing mismatch: %.9g W/m2",
  on_case$forcing_error
)
say(
  "Removal-OFF final maximum forcing mismatch: %.9g W/m2",
  off_case$forcing_error
)
