#!/usr/bin/env Rscript

# V62 matched-non-CO2-forcing Hector 3.5.0 experiment.
#
# The common non-CO2 forcing target is generated by the FaIR job and supplied
# in fair_matched_nonco2_forcing.csv. Hector's total-radiative-forcing
# constraint is iterated to self-consistency so that, for each carbon branch,
#
#   Hector RF_TOTAL(year) - Hector RF_CO2(year) = common target(year)
#
# from 2027 through 2300. Thus the CO2 forcing is allowed to differ between
# removal ON and OFF, while the non-CO2 forcing contribution is identical and
# matched to the same series used in FaIR.

suppressPackageStartupMessages(library(hector))
suppressPackageStartupMessages(library(jsonlite))

options(error = function() {
  cat("\n=== R TRACEBACK ===\n", file = stderr())
  traceback(30)
  quit(save = "no", status = 1, runLast = FALSE)
})

say <- function(...) { cat(sprintf(...), "\n"); flush.console() }
fail <- function(...) stop(sprintf(...), call. = FALSE)

if (as.character(packageVersion("hector")) != "3.5.0") {
  fail("Expected Hector 3.5.0; found %s", as.character(packageVersion("hector")))
}

traj_path <- "external_validation_net_co2_trajectory.csv"
target_path <- "fair_matched_nonco2_forcing.csv"

if (!file.exists(traj_path)) fail("Missing %s", traj_path)
if (!file.exists(target_path)) fail("Missing %s", target_path)

x <- read.csv(traj_path, check.names = FALSE, stringsAsFactors = FALSE)

need <- c(
  "year",
  "gross_co2_gtco2",
  "permafrost_co2_gtco2",
  "stored_carbon_reversal_gtco2",
  "cdr_gtco2",
  "net_co2_gtco2"
)

miss <- setdiff(need, names(x))

if (length(miss)) {
  fail("Trajectory missing columns: %s", paste(miss, collapse = ", "))
}

x <- x[order(x$year), ]

if (min(x$year) != 2026 || max(x$year) != 2183) {
  fail("Expected 2026-2183 canonical trajectory")
}

if (anyDuplicated(x$year)) {
  fail("Duplicate trajectory years")
}

mass_check <-
  x$gross_co2_gtco2 +
  x$permafrost_co2_gtco2 +
  x$stored_carbon_reversal_gtco2 -
  x$cdr_gtco2

mass_err <- max(abs(mass_check - x$net_co2_gtco2))

if (mass_err >= 1e-9) {
  fail("Mass balance failed: %.12g GtCO2", mass_err)
}

last <- x[nrow(x), ]

if (max(x$year) < 2300) {
  yy <- (max(x$year) + 1L):2300L

  ext <- data.frame(
    year = yy,
    gross_co2_gtco2 = rep(last$gross_co2_gtco2, length(yy)),
    permafrost_co2_gtco2 = rep(last$permafrost_co2_gtco2, length(yy)),
    stored_carbon_reversal_gtco2 = rep(last$stored_carbon_reversal_gtco2, length(yy)),
    cdr_gtco2 = rep(last$cdr_gtco2, length(yy)),
    net_co2_gtco2 = rep(last$net_co2_gtco2, length(yy))
  )

  x <- rbind(x[, names(ext)], ext)
}

yrs <- as.numeric(x$year)

if (!identical(yrs, as.numeric(2026:2300))) {
  fail("Extended trajectory must be annual 2026-2300")
}

ft <- read.csv(
  target_path,
  check.names = FALSE,
  stringsAsFactors = FALSE
)

if (!all(c("year", "matched_nonco2_forcing_wm2") %in% names(ft))) {
  fail("Target forcing CSV has wrong columns")
}

ft <- ft[order(ft$year), ]

match_years <- 2027:2300

target <- ft$matched_nonco2_forcing_wm2[
  match(match_years, ft$year)
]

if (length(target) != length(match_years) || any(!is.finite(target))) {
  fail("Common non-CO2 forcing target missing/non-finite over 2027-2300")
}

co2_to_c <- 12.011 / 44.009

gross_source_gtco2 <-
  x$gross_co2_gtco2 +
  x$permafrost_co2_gtco2 +
  x$stored_carbon_reversal_gtco2

gross_c <- gross_source_gtco2 * co2_to_c
cdr_c <- x$cdr_gtco2 * co2_to_c
zero_c <- rep(0, length(yrs))

ini <- system.file(
  "input",
  "hector_ssp245.ini",
  package = "hector"
)

if (!nzchar(ini) || !file.exists(ini)) {
  fail("hector_ssp245.ini not found")
}

unit_ffi <- getunits(FFI_EMISSIONS())
unit_luc <- getunits(LUC_EMISSIONS())
unit_luc_uptake <- getunits(LUC_UPTAKE())
unit_daccs <- getunits(DACCS_UPTAKE())

set_checked <- function(core, dates, var, values, unit, label) {
  tryCatch(
    setvar(core, dates, var, values, unit),
    error = function(e) {
      fail(
        "setvar failed for %s: %s",
        label,
        conditionMessage(e)
      )
    }
  )
}

fetch_one <- function(df, varname) {
  z <- df[
    df$variable == varname,
    c("year", "value")
  ]

  z <- z[order(z$year), ]

  z
}

run_once <- function(
  label,
  removal_on,
  ftotal_constraint = NULL
) {
  core <- newcore(
    ini,
    suppresslogging = TRUE,
    name = label
  )

  on.exit(
    try(shutdown(core), silent = TRUE),
    add = TRUE
  )

  invisible(run(core, 2025))

  set_checked(
    core,
    yrs,
    FFI_EMISSIONS(),
    gross_c,
    unit_ffi,
    "FFI gross source"
  )

  set_checked(
    core,
    yrs,
    LUC_EMISSIONS(),
    zero_c,
    unit_luc,
    "LUC emissions=0"
  )

  set_checked(
    core,
    yrs,
    LUC_UPTAKE(),
    zero_c,
    unit_luc_uptake,
    "LUC uptake=0"
  )

  set_checked(
    core,
    yrs,
    DACCS_UPTAKE(),
    if (removal_on) cdr_c else zero_c,
    unit_daccs,
    if (removal_on) "DACCS=V62 CDR" else "DACCS=0"
  )

  if (!is.null(ftotal_constraint)) {
    if (length(ftotal_constraint) != length(match_years)) {
      fail("Bad Ftot constraint length")
    }

    set_checked(
      core,
      match_years,
      FTOT_CONSTRAIN(),
      ftotal_constraint,
      "W/m2",
      "matched Ftot constraint"
    )
  }

  invisible(run(core, 2300))

  out <- fetchvars(
    core,
    yrs,
    vars = c(
      CONCENTRATIONS_CO2(),
      GLOBAL_TAS(),
      RF_CO2(),
      RF_TOTAL()
    )
  )

  list(
    output = out,
    co2 = fetch_one(out, CONCENTRATIONS_CO2()),
    tas = fetch_one(out, GLOBAL_TAS()),
    rfco2 = fetch_one(out, RF_CO2()),
    rftot = fetch_one(out, RF_TOTAL())
  )
}

# =============================================================================
# UNDER-RELAXED MATCHED-FORCING SOLVER
#
# The old implementation used the complete fixed-point update:
#
#   constraint <- rfco2 + target
#
# which produced numerical oscillation.
#
# This uses the same fixed point but only applies 25% of the correction at
# each iteration. The scientific acceptance tolerance remains 1e-5 W/m2.
# =============================================================================

fit_case <- function(
  label,
  removal_on,
  tol = 1e-5,
  max_iter = 100,
  relax = 0.25
) {
  say("Starting %s unconstrained seed", label)

  if (!is.finite(relax) || relax <= 0 || relax > 1) {
    fail("Invalid relaxation factor %.9g", relax)
  }

  seed <- run_once(
    paste0(label, " seed"),
    removal_on,
    NULL
  )

  rf_seed <- seed$rfco2$value[
    match(match_years, seed$rfco2$year)
  ]

  if (any(!is.finite(rf_seed))) {
    fail("Non-finite seed CO2 forcing")
  }

  constraint <- rf_seed + target

  history <- list()
  final <- NULL

  for (it in seq_len(max_iter)) {
    say("%s forcing iteration %d", label, it)

    z <- run_once(
      sprintf("%s iter%d", label, it),
      removal_on,
      constraint
    )

    rfco2 <- z$rfco2$value[
      match(match_years, z$rfco2$year)
    ]

    rftot <- z$rftot$value[
      match(match_years, z$rftot$year)
    ]

    if (any(!is.finite(rfco2)) || any(!is.finite(rftot))) {
      fail("Non-finite forcing in %s", label)
    }

    eff_non <- rftot - rfco2
    residual <- eff_non - target
    max_res <- max(abs(residual))

    worst_index <- which.max(abs(residual))
    worst_year <- match_years[worst_index]
    worst_residual <- residual[worst_index]

    next_constraint <- rfco2 + target
    raw_update <- next_constraint - constraint
    max_update <- max(abs(raw_update))

    history[[it]] <- list(
      iteration = it,
      relaxation_factor = relax,
      max_abs_nonco2_error_wm2 = max_res,
      max_constraint_update_wm2 = max_update,
      worst_year = worst_year,
      worst_residual_wm2 = worst_residual
    )

    say(
      "  max |effective non-CO2 - target| = %.9g W/m2",
      max_res
    )

    say(
      "  worst year = %d; signed residual = %.9g W/m2",
      worst_year,
      worst_residual
    )

    say(
      "  raw fixed-point update = %.9g W/m2; relaxation = %.3f",
      max_update,
      relax
    )

    final <- z

    if (max_res <= tol) {
      say(
        "%s converged after %d iterations: %.9g <= %.9g W/m2",
        label,
        it,
        max_res,
        tol
      )

      break
    }

    constraint <- constraint + relax * raw_update

    if (any(!is.finite(constraint))) {
      fail(
        "Non-finite damped constraint in %s at iteration %d",
        label,
        it
      )
    }
  }

  if (is.null(final)) {
    fail("No Hector run produced for %s", label)
  }

  hlast <- history[[length(history)]]

  if (hlast$max_abs_nonco2_error_wm2 > tol) {
    fail(
      "%s forcing iteration did not converge after %d iterations: %.9g > %.9g W/m2",
      label,
      max_iter,
      hlast$max_abs_nonco2_error_wm2,
      tol
    )
  }

  list(
    run = final,
    history = history,
    forcing_error = hlast$max_abs_nonco2_error_wm2
  )
}

on_case <- fit_case(
  "removal-ON matched",
  TRUE
)

off_case <- fit_case(
  "removal-OFF matched",
  FALSE
)

co_on <- on_case$run$co2
co_off <- off_case$run$co2

tas_on <- on_case$run$tas
tas_off <- off_case$run$tas

rfco2_on <- on_case$run$rfco2
rfco2_off <- off_case$run$rfco2

rftot_on <- on_case$run$rftot
rftot_off <- off_case$run$rftot

pair <- merge(
  co_on,
  co_off,
  by = "year",
  suffixes = c("_on", "_off")
)

names(pair)[names(pair) == "value_on"] <- "co2_on_ppm"
names(pair)[names(pair) == "value_off"] <- "co2_off_ppm"

pair <- pair[order(pair$year), ]

if (!identical(as.numeric(pair$year), yrs)) {
  fail("Hector paired years mismatch")
}

pair$delta_co2_ppm <-
  pair$co2_off_ppm -
  pair$co2_on_ppm

cum_cdr <- cumsum(
  x$cdr_gtco2
)

pair$cumulative_cdr_gtco2 <- cum_cdr[
  match(pair$year, x$year)
]

gtco2_per_ppm <- 2.124 * (44.009 / 12.011)

pair$apparent_response_fraction <- ifelse(
  pair$cumulative_cdr_gtco2 > 0,
  pair$delta_co2_ppm *
    gtco2_per_ppm /
    pair$cumulative_cdr_gtco2,
  NA_real_
)

if (
  any(!is.finite(pair$co2_on_ppm)) ||
  any(!is.finite(pair$co2_off_ppm))
) {
  fail("Non-finite Hector CO2")
}

if (any(pair$delta_co2_ppm < -1e-8)) {
  fail(
    "Removal ON raises CO2 above OFF beyond tolerance"
  )
}

# Within-model common-state check at 2026.
# CDR is zero in 2026, so both branches must match.

common_2026_co2 <- abs(
  pair$co2_on_ppm[pair$year == 2026] -
  pair$co2_off_ppm[pair$year == 2026]
)

if (
  length(common_2026_co2) != 1 ||
  common_2026_co2 > 1e-8
) {
  fail(
    "Hector 2026 common-state CO2 check failed"
  )
}

common_2026_tas <- abs(
  tas_on$value[tas_on$year == 2026] -
  tas_off$value[tas_off$year == 2026]
)

if (
  length(common_2026_tas) != 1 ||
  common_2026_tas > 1e-8
) {
  fail(
    "Hector 2026 common-state TAS check failed"
  )
}

write.csv(
  pair,
  "hector_matched_attribution.csv",
  row.names = FALSE
)

# Wide state/forcing audit for direct downstream inspection.

audit <- data.frame(
  year = yrs,
  co2_on_ppm = co_on$value,
  co2_off_ppm = co_off$value,
  tas_on_c = tas_on$value,
  tas_off_c = tas_off$value,
  rfco2_on_wm2 = rfco2_on$value,
  rfco2_off_wm2 = rfco2_off$value,
  rftot_on_wm2 = rftot_on$value,
  rftot_off_wm2 = rftot_off$value
)

target_full <- ft$matched_nonco2_forcing_wm2[
  match(yrs, ft$year)
]

audit$target_nonco2_wm2 <- target_full

audit$effective_nonco2_on_wm2 <-
  audit$rftot_on_wm2 -
  audit$rfco2_on_wm2

audit$effective_nonco2_off_wm2 <-
  audit$rftot_off_wm2 -
  audit$rfco2_off_wm2

write.csv(
  audit,
  "hector_matched_timeseries.csv",
  row.names = FALSE
)

getv <- function(col, y) {
  z <- pair[
    pair$year == y,
    col
  ]

  if (length(z) != 1) {
    return(NA_real_)
  }

  as.numeric(z)
}

milestones <- list()

for (yy in c(
  2040,
  2100,
  2156,
  2184,
  2200,
  2300
)) {
  milestones[[as.character(yy)]] <- list(
    delta_co2_ppm =
      getv(
        "delta_co2_ppm",
        yy
      ),

    response_fraction =
      getv(
        "apparent_response_fraction",
        yy
      )
  )
}

summary <- list(
  model = "Hector",

  version = "3.5.0",

  experiment =
    "V62 removal-ON/OFF with FaIR-derived harmonized non-CO2 ERF after 2026",

  common_nonco2_target =
    "fair_matched_nonco2_forcing.csv generated by the FaIR matched-forcing job",

  implementation = paste0(
    "For each carbon branch, Hector Ftot_constrain is iterated until ",
    "RF_TOTAL - RF_CO2 equals the common target for 2027-2300. ",
    "CO2 forcing remains branch-specific. ",
    "A 0.25 under-relaxation factor is used for numerical convergence."
  ),

  match_starts = 2027,

  common_state_2026_co2_abs_error_ppm =
    common_2026_co2,

  common_state_2026_tas_abs_error_c =
    common_2026_tas,

  forcing_match_tolerance_wm2 =
    1e-5,

  forcing_match_max_abs_on_wm2 =
    on_case$forcing_error,

  forcing_match_max_abs_off_wm2 =
    off_case$forcing_error,

  fit_iterations_on =
    on_case$history,

  fit_iterations_off =
    off_case$history,

  trajectory_mass_balance_max_abs_gtco2 =
    mass_err,

  canonical_cdr_2026_2183_gtco2 =
    sum(
      x$cdr_gtco2[
        x$year <= 2183
      ]
    ),

  peak_cdr_2026_2183_gtco2_per_year =
    max(
      x$cdr_gtco2[
        x$year <= 2183
      ]
    ),

  milestones =
    milestones,

  interpretation_boundary = paste0(
    "The future non-CO2 forcing contribution is harmonized to FaIR. ",
    "Hector retains its own carbon-cycle parameters, historical carbon pools, ",
    "and CO2 forcing formulation. Cross-model disagreement is a result, ",
    "not an automatic failure gate."
  )
)

write_json(
  summary,
  "hector_matched_summary.json",
  pretty = TRUE,
  auto_unbox = TRUE,
  digits = NA
)

cat(
  toJSON(
    summary,
    pretty = TRUE,
    auto_unbox = TRUE,
    digits = NA
  ),
  "\n"
)
